"""Add slides_json to Presentation

Revision ID: 805c3551b078
Revises: d690676fbd5b
Create Date: 2025-05-19 23:01:04.858451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805c3551b078'
down_revision = 'd690676fbd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slides_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.drop_column('slides_json')

    # ### end Alembic commands ###
